name: Download

on: 
  push:
    branches: 
      - master # build master branch only

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Download
      run: |
        mkdir download
        cd download
        mkdir re
        cd re
        curl -O 'https://github.com/NickeManarin/ScreenToGif/releases/download/2.26.1/ScreenToGif.2.26.1.Portable.zip'
        cd ..
        tar cjf - re/ |split -b 20m - screentogif.tar.bz2.
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./download
